import {
  PanchayatResponse,
  BlockItem,
  PanchayatFullDetail,
  PanchayatWeatherSummary,
  GridCellRecord,
  RiskResult,
  AdvisoryResult,
  RiskSubsystemStatus,
  AdvisorySubsystemStatus,
  ModelSummary,
  ModelMetricsSummary,
  FeatureImportanceItem,
} from '../types/index.js';

export const mockBlocks: BlockItem[] = [
  {
    id: 1,
    lgd_code: 'BLK_UP_001',
    name: 'Faizabad Sadar Block',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    panchayats_count: 4,
  },
  {
    id: 2,
    lgd_code: 'BLK_UP_002',
    name: 'Bikapur Block',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    panchayats_count: 3,
  },
  {
    id: 3,
    lgd_code: 'BLK_UP_003',
    name: 'Milkipur Block',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    panchayats_count: 3,
  },
];

export const mockPanchayats: PanchayatResponse[] = [
  {
    panchayat_id: 'GP_ADV_01',
    name: 'Sohawal',
    block_id: '1',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    latitude: 26.782,
    longitude: 82.015,
    elevation_meters: 112.5,
    land_use: {
      total_area_hectares: 1000.0,
      cropland_area_hectares: 820.0,
      forest_area_hectares: 80.0,
      urban_area_hectares: 50.0,
      water_bodies_hectares: 30.0,
      barren_area_hectares: 20.0,
      is_agricultural_eligible: true,
    },
  },
  {
    panchayat_id: 'GP_ADV_02',
    name: 'Bikapur Rural',
    block_id: '1',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    latitude: 26.605,
    longitude: 82.135,
    elevation_meters: 108.0,
    land_use: {
      total_area_hectares: 900.0,
      cropland_area_hectares: 710.0,
      forest_area_hectares: 90.0,
      urban_area_hectares: 40.0,
      water_bodies_hectares: 35.0,
      barren_area_hectares: 25.0,
      is_agricultural_eligible: true,
    },
  },
  {
    panchayat_id: 'GP_ADV_03',
    name: 'Milkipur Khas',
    block_id: '1',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    latitude: 26.582,
    longitude: 81.912,
    elevation_meters: 115.0,
    land_use: {
      total_area_hectares: 750.0,
      cropland_area_hectares: 580.0,
      forest_area_hectares: 100.0,
      urban_area_hectares: 30.0,
      water_bodies_hectares: 25.0,
      barren_area_hectares: 15.0,
      is_agricultural_eligible: true,
    },
  },
  {
    panchayat_id: 'GP_ADV_04',
    name: 'Ayodhya Cantt Zone',
    block_id: '1',
    district_name: 'Ayodhya',
    state_name: 'Uttar Pradesh',
    latitude: 26.795,
    longitude: 82.195,
    elevation_meters: 110.0,
    land_use: {
      total_area_hectares: 1500.0,
      cropland_area_hectares: 0.0,
      forest_area_hectares: 120.0,
      urban_area_hectares: 1280.0,
      water_bodies_hectares: 80.0,
      barren_area_hectares: 20.0,
      is_agricultural_eligible: false,
    },
  },
];

export const mockRisks: RiskResult[] = [
  {
    id: 101,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 1,
    crop_name: 'Rice',
    stage_name: 'Flowering',
    risk_type: 'HEAT_STRESS',
    risk_category: 'THERMAL',
    status: 'DETECTED',
    severity: 'HIGH',
    risk_score: 0.82,
    observed_value: 38.5,
    threshold_value: 37.0,
    unit: '°C',
    duration_hours: 24,
    confidence: 'HIGH',
    rule_version: 'agri_risk_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_CRITERIA',
    evidence: {
      observed_value: 38.5,
      threshold_value: 37.0,
      unit: '°C',
      crop_name: 'Rice',
      stage_name: 'Flowering',
      condition_description: 'Max temperature of 38.5°C exceeded critical flowering threshold of 37.0°C.',
      metrics: { max_temp_c: 38.5, min_temp_c: 28.0, mean_temp_c: 33.2 },
    },
    evaluation_date: '2026-07-15T00:00:00Z',
  },
  {
    id: 102,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 2,
    crop_name: 'Maize',
    stage_name: 'Tasseling/Silking',
    risk_type: 'HEAT_STRESS',
    risk_category: 'THERMAL',
    status: 'DETECTED',
    severity: 'HIGH',
    risk_score: 0.78,
    observed_value: 38.5,
    threshold_value: 38.0,
    unit: '°C',
    duration_hours: 24,
    confidence: 'HIGH',
    rule_version: 'agri_risk_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_CRITERIA',
    evidence: {
      observed_value: 38.5,
      threshold_value: 38.0,
      unit: '°C',
      crop_name: 'Maize',
      stage_name: 'Tasseling/Silking',
      condition_description: 'Max temperature of 38.5°C exceeded maize tasseling threshold of 38.0°C.',
      metrics: { max_temp_c: 38.5, min_temp_c: 28.0 },
    },
    evaluation_date: '2026-07-15T00:00:00Z',
  },
  {
    id: 103,
    panchayat_id: 2,
    panchayat_name: 'Bikapur Rural',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 3,
    crop_name: 'Wheat',
    stage_name: 'Heading/Flowering',
    risk_type: 'COLD_STRESS',
    risk_category: 'THERMAL',
    status: 'DETECTED',
    severity: 'HIGH',
    risk_score: 0.85,
    observed_value: 1.5,
    threshold_value: 2.0,
    unit: '°C',
    duration_hours: 24,
    confidence: 'HIGH',
    rule_version: 'agri_risk_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_CRITERIA',
    evidence: {
      observed_value: 1.5,
      threshold_value: 2.0,
      unit: '°C',
      crop_name: 'Wheat',
      stage_name: 'Heading/Flowering',
      condition_description: 'Min temperature of 1.5°C fell below critical frost threshold of 2.0°C.',
      metrics: { min_temp_c: 1.5, max_temp_c: 18.0 },
    },
    evaluation_date: '2026-07-15T00:00:00Z',
  },
  {
    id: 104,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 1,
    crop_name: 'Rice',
    stage_name: 'Flowering',
    risk_type: 'DISEASE_FAVORABLE_CONDITIONS',
    risk_category: 'PATHOLOGICAL_ENVIRONMENT',
    status: 'DETECTED',
    severity: 'MODERATE',
    risk_score: 0.65,
    observed_value: 33.2,
    threshold_value: 22.0,
    unit: '°C',
    duration_hours: 24,
    confidence: 'MEDIUM',
    rule_version: 'agri_risk_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_CRITERIA',
    evidence: {
      observed_value: 33.2,
      threshold_value: 22.0,
      unit: '°C',
      crop_name: 'Rice',
      stage_name: 'Flowering',
      condition_description: 'Environmental mean temperature (33.2°C) is within favorable pathogen proliferation range. Note: Indicates environmental suitability only, NOT confirmed disease.',
      metrics: { mean_temp_c: 33.2 },
    },
    evaluation_date: '2026-07-15T00:00:00Z',
  },
];

export const mockAdvisories: AdvisoryResult[] = [
  {
    id: 201,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 1,
    crop_name: 'Rice',
    stage_name: 'Flowering',
    risk_log_id: 101,
    advisory_type: 'HEAT_STRESS_ADVISORY',
    advisory_category: 'ACTION_ADVISORY',
    priority: 'HIGH',
    priority_rank: 1,
    priority_reason: 'Ranked #1 for Rice based on priority HIGH and hazard severity HIGH.',
    title: 'High Heat Stress Advisory for Rice during Flowering',
    message: 'Forecast maximum temperature of 38.5°C indicates high heat stress risk for rice during the flowering stage, which may impair pollination and increase spikelet sterility.',
    action: {
      action_category: 'WATER_MANAGEMENT',
      action_text: 'Maintain 5-7 cm standing water layer in paddy fields to moderate canopy micro-temperature during peak sunshine hours. Consider light foliar spray of potassium chloride (1%) or ascorbic acid to alleviate canopy thermal stress, subject to local agromet guidance.',
      timing: 'Early morning or late afternoon before peak heat',
      urgency: 'IMMEDIATE',
      conditions: { stage: 'Flowering', severity: 'HIGH' },
    },
    rationale: 'Elevated daytime temperatures (≥ 37.0°C) during anthesis inhibit anther dehiscence and pollen viability.',
    severity: 'HIGH',
    confidence: 'HIGH',
    confidence_reason: 'Inherited from Phase 10 HEAT_STRESS risk confidence (HIGH). Stage resolved: True.',
    valid_from: '2026-07-15T00:00:00Z',
    valid_until: '2026-07-15T23:59:59Z',
    forecast_date: '2026-07-15T00:00:00Z',
    issue_time: '2026-07-15T06:00:00Z',
    source_model: 'IMD-GFS',
    rule_version: 'agri_risk_v1.0.0',
    advisory_rule_version: 'agri_advisory_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_GUIDELINES',
    language: 'en',
    status: 'ACTIVE',
    is_expert_review_required: false,
    is_cropland_eligible: true,
  },
  {
    id: 202,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 2,
    crop_name: 'Maize',
    stage_name: 'Tasseling/Silking',
    risk_log_id: 102,
    advisory_type: 'HEAT_STRESS_ADVISORY',
    advisory_category: 'ACTION_ADVISORY',
    priority: 'HIGH',
    priority_rank: 1,
    priority_reason: 'Ranked #1 for Maize based on priority HIGH and hazard severity HIGH.',
    title: 'Heat Stress Advisory for Maize during Tasseling/Silking',
    message: 'Forecast maximum temperature of 38.5°C during maize tasseling/silking may cause tassel blasting and poor grain setting.',
    action: {
      action_category: 'WATER_MANAGEMENT',
      action_text: 'Apply irrigation at tasseling and silking stages to maintain root-zone moisture and protect silk receptivity.',
      timing: 'Morning or late evening',
      urgency: 'IMMEDIATE',
      conditions: { stage: 'Tasseling/Silking', severity: 'HIGH' },
    },
    rationale: 'High thermal regime (38.5°C) during pollination impairs pollen viability and silk hydration.',
    severity: 'HIGH',
    confidence: 'HIGH',
    valid_from: '2026-07-15T00:00:00Z',
    valid_until: '2026-07-15T23:59:59Z',
    forecast_date: '2026-07-15T00:00:00Z',
    issue_time: '2026-07-15T06:00:00Z',
    source_model: 'IMD-GFS',
    rule_version: 'agri_risk_v1.0.0',
    advisory_rule_version: 'agri_advisory_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_GUIDELINES',
    language: 'en',
    status: 'ACTIVE',
    is_expert_review_required: false,
    is_cropland_eligible: true,
  },
  {
    id: 203,
    panchayat_id: 2,
    panchayat_name: 'Bikapur Rural',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 3,
    crop_name: 'Wheat',
    stage_name: 'Heading/Flowering',
    risk_log_id: 103,
    advisory_type: 'COLD_STRESS_ADVISORY',
    advisory_category: 'ACTION_ADVISORY',
    priority: 'CRITICAL',
    priority_rank: 1,
    priority_reason: 'Ranked #1 for Wheat based on frost hazard severity HIGH during reproductive heading.',
    title: 'Frost and Cold Injury Advisory for Wheat during Heading',
    message: 'Forecast minimum temperature of 1.5°C indicates severe chilling and potential frost injury for wheat at heading/flowering.',
    action: {
      action_category: 'FIELD_OPERATIONS',
      action_text: 'Apply light irrigation in the evening to elevate field soil and air temperature. Create light smoke screens (by burning agricultural waste/straw around field boundaries) during pre-dawn hours to prevent radiation frost.',
      timing: 'Evening before cold night / pre-dawn',
      urgency: 'IMMEDIATE',
      conditions: { stage: 'Heading/Flowering', severity: 'HIGH' },
    },
    rationale: 'Sub-zero or near-freezing temperatures (≤ 2.0°C) cause ice crystal formation in reproductive organs, leading to floret sterility.',
    severity: 'HIGH',
    confidence: 'HIGH',
    valid_from: '2026-07-15T00:00:00Z',
    valid_until: '2026-07-15T23:59:59Z',
    forecast_date: '2026-07-15T00:00:00Z',
    issue_time: '2026-07-15T06:00:00Z',
    source_model: 'IMD-GFS',
    rule_version: 'agri_risk_v1.0.0',
    advisory_rule_version: 'agri_advisory_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_GUIDELINES',
    language: 'en',
    status: 'ACTIVE',
    is_expert_review_required: false,
    is_cropland_eligible: true,
  },
  {
    id: 204,
    panchayat_id: 1,
    panchayat_name: 'Sohawal',
    block_id: 1,
    block_name: 'Faizabad Sadar Block',
    crop_id: 1,
    crop_name: 'Rice',
    stage_name: 'Flowering',
    risk_log_id: 104,
    advisory_type: 'DISEASE_FAVORABLE_CONDITIONS_ADVISORY',
    advisory_category: 'ACTION_ADVISORY',
    priority: 'MEDIUM',
    priority_rank: 2,
    priority_reason: 'Ranked #2 for Rice behind High Heat Stress.',
    title: 'Environmental Alert: Favorable Conditions for Foliar Pathogens',
    message: 'Forecast micro-climatic conditions (mean temperature around 33.2°C with high relative humidity) are favorable for foliar fungal and bacterial pathogen proliferation. Note: This indicates environmental suitability, NOT a confirmed crop disease diagnosis.',
    action: {
      action_category: 'DISEASE_MONITORING',
      action_text: 'Inspect standing crops regularly for early symptom development (e.g. leaf spots, blights, or rusts). Follow recommended cultural sanitation practices and consult local agricultural extension officers for approved crop-protection measures if symptoms appear.',
      timing: 'During regular morning crop scouting',
      urgency: 'UPCOMING',
      conditions: { stage: 'Flowering' },
    },
    rationale: 'Environmental temperature (33.2°C) within favorable pathogen window (22-32°C).',
    severity: 'MODERATE',
    confidence: 'MEDIUM',
    valid_from: '2026-07-15T00:00:00Z',
    valid_until: '2026-07-15T23:59:59Z',
    forecast_date: '2026-07-15T00:00:00Z',
    issue_time: '2026-07-15T06:00:00Z',
    source_model: 'IMD-GFS',
    rule_version: 'agri_risk_v1.0.0',
    advisory_rule_version: 'agri_advisory_v1.0.0',
    rule_source: 'ICAR_IMD_AGROMET_GUIDELINES',
    language: 'en',
    status: 'ACTIVE',
    is_expert_review_required: false,
    is_cropland_eligible: true,
  },
];

export const mockGridCells: GridCellRecord[] = (() => {
  const cells: GridCellRecord[] = [];
  const baseLat = 26.78;
  const baseLon = 82.015;
  const coarseTemp = 36.5;
  let id = 1;

  for (let i = -3; i <= 3; i++) {
    for (let j = -3; j <= 3; j++) {
      const lat = Number((baseLat + i * 0.009).toFixed(5));
      const lon = Number((baseLon + j * 0.009).toFixed(5));
      const elev = Number((112.0 + i * 2.5 + j * 1.8).toFixed(1));
      const slope = Number((Math.abs(i * 0.8) + Math.abs(j * 0.6)).toFixed(1));
      const residual = Number((-0.0065 * (elev - 112.0) + (i > 0 ? 0.4 : -0.3)).toFixed(2));
      const downscaled = Number((coarseTemp + residual).toFixed(2));

      cells.push({
        cell_id: `GRID_1KM_${id.toString().padStart(3, '0')}`,
        latitude: lat,
        longitude: lon,
        elevation_m: elev,
        slope_deg: slope,
        aspect_deg: 180.0,
        cropland_fraction: 0.82,
        coarse_temperature_c: coarseTemp,
        predicted_residual_c: residual,
        downscaled_temperature_c: downscaled,
        model_version: 'v1.0.0',
        quality_flag: 'VALID',
      });
      id++;
    }
  }
  return cells;
})();

export const mockModelMetrics: ModelMetricsSummary = {
  model_version: 'v1.0.0',
  dataset_version: 'v1.1.0',
  train_mae: 0.42,
  val_mae: 0.58,
  test_mae: 0.64,
  test_rmse: 0.89,
  test_r2: 0.91,
  baseline_coarse_mae: 2.34,
  improvement_over_baseline_pct: 72.6,
};

export const mockFeatureImportances: FeatureImportanceItem[] = [
  { feature_name: 'elevation_m (DEM Height)', importance: 0.38, rank: 1 },
  { feature_name: 'slope_deg (Topographic Slope)', importance: 0.22, rank: 2 },
  { feature_name: 'cropland_fraction (LULC Agriculture)', importance: 0.16, rank: 3 },
  { feature_name: 'urban_fraction (LULC Heat Island)', importance: 0.11, rank: 4 },
  { feature_name: 'doy_sin (Cyclical Day of Year)', importance: 0.08, rank: 5 },
  { feature_name: 'aspect_deg (Terrain Aspect)', importance: 0.05, rank: 6 },
];
