from app.schemas.common import APIResponse, ErrorDetail, ErrorResponse, PaginationParams, PaginatedResponse
from app.schemas.health import HealthCheckResponse, ComponentStatus
from app.schemas.weather import BlockWeatherForecast, DownscaledPanchayatWeather
from app.schemas.panchayat import PanchayatBase, PanchayatResponse, LandUseComposition
from app.schemas.agriculture import (
    CropContext,
    CropStageInfo,
    SoilProfile,
    CropStageContext,
    SoilContextSummary,
    WeatherContextSummary,
    PanchayatCropContextSummary,
    AgriculturalContextRequest,
    AgriculturalContextResponse,
    PanchayatAgriculturalProfile,
    AgricultureSubsystemStatus,
)
from app.schemas.advisory import (
    AgroAdvisoryReport,
    AgriculturalRisk,
    AgroAdvisoryAction,
    RiskStatus,
    RiskSeverity,
    RiskType,
    RiskCategory,
    RiskEvidence,
    RiskResult,
    RiskEvaluationRequest,
    RiskEvaluationResponse,
    PanchayatRiskProfile,
    RiskSubsystemStatus,
    AdvisoryType,
    AdvisoryCategory,
    AdvisoryPriority,
    AdvisoryStatus,
    AdvisoryActionCategory,
    AdvisoryUrgency,
    AdvisoryAction,
    AdvisoryResult,
    AdvisoryGenerationRequest,
    AdvisoryGenerationResponse,
    PanchayatAdvisoryProfile,
    AdvisorySubsystemStatus,
    NowcastAdvisoryState,
    LocalizedPrecipitationAdvisoryEvidence,
    NowcastAdvisoryExplanation,
)
from app.schemas.panchayat_boundary import (
    BoundaryResolutionStatus,
    PointLocationStatus,
    PanchayatBoundaryRecord,
    BoundaryResolutionResponse,
    PanchayatBoundaryFeatureResponse,
)
from app.schemas.spatial_masking import (
    VariableType,
    CoverageQuality,
    SourceResolutionProvenance,
    SourceGridCell,
    SourceWeatherGrid,
    CellIntersectionResult,
    ContinuousVariableFeatures,
    PrecipitationVariableFeatures,
    PanchayatSpatialExtractionResult,
)
from app.schemas.satellite import (
    SatelliteProductType,
    SatelliteObservationStatus,
    SatelliteProvenance,
    SatelliteCloudFeatures,
    SatelliteTemporalDelta,
    PanchayatSatelliteExtractionResult,
)
from app.schemas.precipitation_nowcast import (
    PrecipitationSourceState,
    NowcastConfidence,
    EvidenceSignalType,
    PrecipitationEvidenceComponent,
    RadarObservationFeatures,
    SurfaceObservationFeatures,
    BaselinePrecipitationExpectation,
    PrecipitationNowcastHorizonResult,
    PrecipitationNowcastProvenance,
    PanchayatPrecipitationNowcastResult,
)



__all__ = [
    "APIResponse",
    "ErrorDetail",
    "ErrorResponse",
    "PaginationParams",
    "PaginatedResponse",
    "HealthCheckResponse",
    "ComponentStatus",
    "BlockWeatherForecast",
    "DownscaledPanchayatWeather",
    "PanchayatBase",
    "PanchayatResponse",
    "LandUseComposition",
    "BoundaryResolutionStatus",
    "PointLocationStatus",
    "PanchayatBoundaryRecord",
    "BoundaryResolutionResponse",
    "PanchayatBoundaryFeatureResponse",
    "VariableType",
    "CoverageQuality",
    "SourceResolutionProvenance",
    "SourceGridCell",
    "SourceWeatherGrid",
    "CellIntersectionResult",
    "ContinuousVariableFeatures",
    "PrecipitationVariableFeatures",
    "PanchayatSpatialExtractionResult",
    "SatelliteProductType",
    "SatelliteObservationStatus",
    "SatelliteProvenance",
    "SatelliteCloudFeatures",
    "SatelliteTemporalDelta",
    "PanchayatSatelliteExtractionResult",
    "PrecipitationSourceState",
    "NowcastConfidence",
    "EvidenceSignalType",
    "PrecipitationEvidenceComponent",
    "RadarObservationFeatures",
    "SurfaceObservationFeatures",
    "BaselinePrecipitationExpectation",
    "PrecipitationNowcastHorizonResult",
    "PrecipitationNowcastProvenance",
    "PanchayatPrecipitationNowcastResult",
    "CropContext",


    "CropStageInfo",
    "SoilProfile",
    "CropStageContext",
    "SoilContextSummary",
    "WeatherContextSummary",
    "PanchayatCropContextSummary",
    "AgriculturalContextRequest",
    "AgriculturalContextResponse",
    "PanchayatAgriculturalProfile",
    "AgricultureSubsystemStatus",
    "RiskStatus",
    "RiskSeverity",
    "RiskType",
    "RiskCategory",
    "RiskEvidence",
    "RiskResult",
    "RiskEvaluationRequest",
    "RiskEvaluationResponse",
    "PanchayatRiskProfile",
    "RiskSubsystemStatus",
    "AgroAdvisoryReport",
    "AgriculturalRisk",
    "AgroAdvisoryAction",
    "AdvisoryType",
    "AdvisoryCategory",
    "AdvisoryPriority",
    "AdvisoryStatus",
    "AdvisoryActionCategory",
    "AdvisoryUrgency",
    "AdvisoryAction",
    "AdvisoryResult",
    "AdvisoryGenerationRequest",
    "AdvisoryGenerationResponse",
    "PanchayatAdvisoryProfile",
    "AdvisorySubsystemStatus",
    "NowcastAdvisoryState",
    "LocalizedPrecipitationAdvisoryEvidence",
    "NowcastAdvisoryExplanation",
]

